services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    shm_size: 1g

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: development@northernexplorer.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 500
    ports:
      - "5433:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres-data:
  pgadmin-data:
