export const m20260705: string[] = [
    `alter table "city_cache" alter column "lat" type double precision using ("lat"::double precision);`,
    `alter table "city_cache" alter column "lon" type double precision using ("lon"::double precision);`,
    `alter table "city_cache" alter column "city_data" type jsonb using ("city_data"::jsonb);`,
    `alter table "forecast_cache" alter column "lat" type double precision using ("lat"::double precision);`,
    `alter table "forecast_cache" alter column "lon" type double precision using ("lon"::double precision);`,
    `alter table "forecast_cache" alter column "forecast_data" type jsonb using ("forecast_data"::jsonb);`,
    `alter table "historic_site" alter column "lat" type double precision using ("lat"::double precision);`,
    `alter table "historic_site" alter column "lon" type double precision using ("lon"::double precision);`,
    `alter table "user" add "last_login_at" timestamptz null, add "is_active" boolean not null;`,
    `alter table "user" rename column "email_activated_at" to "password_hash";`,
    `alter table "user" add constraint "user_user_name_unique" unique ("user_name");`,
    `alter table "user" add constraint "user_email_unique" unique ("email");`,
    `alter table "weather_cache" alter column "lat" type double precision using ("lat"::double precision);`,
    `alter table "weather_cache" alter column "lon" type double precision using ("lon"::double precision);`,
    `alter table "weather_cache" alter column "weather_data" type jsonb using ("weather_data"::jsonb);`,
    `create sequence if not exists "user_id_seq";`,
    `alter table "user" alter column "id" set default nextval('user_id_seq');`,
];
