import {StyleSheet, Platform} from 'react-native';

export const styles = StyleSheet.create({
	bannerContainer: {
		position: 'relative',
		height: 240,
		width: '100%',
	},
	banner: {
		width: '100%',
		height: '100%',
	},
	mapCard: {
		position: 'absolute',
		bottom: 16,
		right: 16,
		width: 120,
		height: 120,
		borderRadius: 12,
		overflow: 'hidden',
		borderWidth: 2,
		borderColor: '#ffffff',
		shadowColor: '#000',
		shadowOffset: {width: 0, height: 4},
		shadowOpacity: 0.3,
		shadowRadius: 6,
		elevation: 6,
	},
	content: {
		padding: 24,
	},
	breadcrumbs: {
		color: '#0088cc',
		fontSize: 12,
		fontWeight: '600',
		textTransform: 'uppercase',
		letterSpacing: 1,
	},
	title: {
		color: '#0f172a',
		fontSize: 26,
		fontWeight: '700',
		marginTop: 8,
	},
	metaContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		alignItems: 'center',
	},
	metaLabel: {
		color: '#64748b',
		fontSize: 13,
		marginTop: 6,
		fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
		paddingRight: 20,
	},
	divider: {
		height: 1,
		backgroundColor: '#f1f5f9',
		marginVertical: 20,
	},
	body: {
		fontSize: 16,
		lineHeight: 26,
		color: '#334155',
	},

	// --- REVIEWS LISTING ---
	reviewCard: {
		backgroundColor: '#ffffff',
		borderRadius: 16,
		padding: 18,
		marginVertical: 8,
		borderWidth: 1,
		borderColor: '#f1f5f9',
		shadowColor: '#0f172a',
		shadowOffset: {width: 0, height: 4},
		shadowOpacity: 0.03,
		shadowRadius: 12,
		elevation: 2,
	},
	headerRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	userName: {
		fontSize: 15,
		fontWeight: '600',
		color: '#0f172a',
	},
	score: {
		fontSize: 14,
		fontWeight: '600',
		color: '#0088cc',
	},
	description: {
		marginTop: 10,
		fontSize: 15,
		lineHeight: 22,
		color: '#475569',
	},
	editButton: {
		paddingHorizontal: 12,
		paddingVertical: 6,
		backgroundColor: '#f0f9ff',
		borderRadius: 8,
	},
	editButtonText: {
		color: '#0088cc',
		fontWeight: '600',
		fontSize: 13,
	},

	// --- MODERNIZED REVIEW FORM ---
	reviewFormContainer: {
		backgroundColor: '#ffffff',
		borderRadius: 20,
		padding: 24,
		marginTop: 24,
		borderWidth: 1,
		borderColor: '#f1f5f9',
		shadowColor: '#0f172a',
		shadowOffset: {width: 0, height: 8},
		shadowOpacity: 0.04,
		shadowRadius: 16,
		elevation: 3,
	},
	reviewTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#0f172a',
		textAlign: 'center',
		marginBottom: 4,
	},
	fieldWrapper: {
		marginVertical: 12,
	},
	submitButton: {
		backgroundColor: '#0088cc',
		paddingVertical: 14,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 8,
		shadowColor: '#0088cc',
		shadowOffset: {width: 0, height: 4},
		shadowOpacity: 0.2,
		shadowRadius: 8,
		elevation: 3,
	},
	submitButtonPressed: {
		opacity: 0.85,
		transform: [{scale: 0.995}],
	},
	submitButtonDisabled: {
		opacity: 0.5,
		shadowOpacity: 0,
	},
	submitButtonText: {
		color: '#ffffff',
		fontSize: 15,
		fontWeight: '600',
		letterSpacing: 0.3,
	},
	errorBanner: {
		backgroundColor: '#fef2f2',
		borderRadius: 10,
		padding: 12,
		marginVertical: 10,
	},
	errorBannerText: {
		color: '#ef4444',
		fontSize: 13,
		fontWeight: '500',
		textAlign: 'center',
	},
	errorText: {
		color: '#ef4444',
		fontSize: 12,
		fontWeight: '500',
		marginTop: 6,
		textAlign: 'center',
	},
});
