export const m20261010: string[] = [
	`create table "point_of_interest_suggestion" (
		"id" uuid not null,
		"version" int not null default 1,
		"name" text not null,
		"description" text not null,
		"lat" double precision not null,
		"lon" double precision not null,
		"start_date" double precision null,
		"end_date" double precision null,
		"type" text[] not null,
		"status" text not null default 'Pending',
		"created_at" timestamptz not null,
		"updated_at" timestamptz not null,
		"user_id" uuid not null,
		"point_of_interest_id" uuid not null,
		"country_id" uuid not null,
		"region_id" uuid not null,
		"organization_id" uuid not null,
		"image_id" uuid null,
		primary key ("id")
	);`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_user_id_foreign" foreign key ("user_id") references "user" ("id");`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_point_of_interest_id_foreign" foreign key ("point_of_interest_id") references "point_of_interest" ("id") on delete cascade;`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_country_id_foreign" foreign key ("country_id") references "country" ("id");`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_region_id_foreign" foreign key ("region_id") references "region" ("id");`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_organization_id_foreign" foreign key ("organization_id") references "organization" ("id");`,
	`alter table "point_of_interest_suggestion" add constraint "point_of_interest_suggestion_image_id_foreign" foreign key ("image_id") references "image" ("id");`,
	`create index "idx_point_of_interest_suggestion_status" on "point_of_interest_suggestion" ("status");`,
	`create index "idx_point_of_interest_suggestion_poi_id" on "point_of_interest_suggestion" ("point_of_interest_id");`,
	`create index "idx_point_of_interest_suggestion_user_id" on "point_of_interest_suggestion" ("user_id");`,
];
